export {default as Navbar } from './Navbar'
export {default as Hero } from './Hero'
export {default as Skills } from './Skills'
export {default as SectionTitle } from './SectionTitle'
export {default as SkillsCard } from './SkillsCard'
export {default as About } from './About'
export {default as Projects } from './Projects'
export {default as ProjectsCard } from './ProjectsCard'